# Site settings
title: UXC LAB Researcher
baseurl: " "
url: https://kjhwan98.github.io/
google_analytics: # Tracking ID, e.g. "UA-000000-01"

# Author
author:
  name: JaeHwan KIM
  desc: Hello, I am studying for a master degree in the Department of Software Convergence at KyungHee University.
  email: jhwankim@khu.ac.kr
  selfie: assets/img/prof.jpg

# social
social:
  email: true
  behance:
  bitbucket:
  dribbble:
  facebook: 
  flickr:
  github: kjhwan98
  google_plus:
  instagram:
  keybase:
  linkedin: https://www.linkedin.com/in/jaehwan-kim-25a188280 
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:
  steam:
  tumblr:
  gitlab:
  twitter:
  vimeo:
  wordpress:
  youtube:
  default_txt: "Follow On"

# Build settings
markdown: kramdown

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink: /:year-:month-:day/:title
paginate_path: "/portfolio/page:num/"
paginate: 5
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gem"
  - "LICENSE"
  - "READE.md"
  - "screenshot.png"
